apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: argocd
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
      - values.k8s-new.yaml
    path: istio
    repoURL: https://github.com/rockman88v/bds_platform.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
